FROM severalcontainers-dev.azurecr.io/secure-alpine-dev:latest

ENV APP_PORT=5173

WORKDIR /app/client

COPY ./client .

RUN npm install

EXPOSE $APP_PORT

CMD ["sh", "-c", "npm run dev -- --port $APP_PORT --host 0.0.0.0"]
