name: Deploy to azure web app - Source # Name of the workflow
on:
  push:
    branches: [ main ] # Trigger workflow on git push to main branch
  workflow_dispatch: # Allow manual invocation of the workflow

jobs:  
  build-and-deploy:
    runs-on: windows-latest
    
    steps:            
      - name: Log in with Azure credentials
        uses: azure/login@v1 # Log in with azure Credentials
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'


          # ------------------- ^^ ABOVE IS CORRECTED ^^ -----------------------
          # --------------------- BELOW IS NOT CHANGED -------------------------
                    
      - name: Deploy to App Runner
        id: deploy-apprunner
        uses: awslabs/amazon-app-runner-deploy@main # Deploy app runner service
        with:
          service: app-runner-git-deploy-service
          source-connection-arn: ${{ secrets.AWS_CONNECTION_SOURCE_ARN }}
          repo: https://github.com/${{ github.repository }}
          branch: ${{ github.ref }}
          runtime: PYTHON_3
          build-command: pip install -r requirements.txt
          start-command: python app.py
          port: 5000
          region: ${{ vars.AWS_REGION }}
          cpu : 1
          memory : 2
          wait-for-service-stability-seconds: 600
      
      - name: App Runner output
        run: echo "App runner output ${{ steps.deploy-apprunner.outputs.service-id }}" 